ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /app

#accept dynamic argument
ARG APP_VERSION
ENV APP_VERSION=${APP_VERSION}

#SET ENIVIRMENT VARIABLE
ENV ENIVIRMENT=production

COPY . .

CMD ["python","app.py"]